### ISSUE TITLE
./bin/biwas does not work with latest Node

### ISSUE THREAD

**Issue by yhara** [biwascheme/biwascheme#191]
```
% ./bin/biwas
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/yhara/Dropbox/proj/biwascheme/bin/biwas
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:101:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:31)
    at async Loader.import (internal/modules/esm/loader.js:164:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by yhara** [comment]
Does not reproduce with node v14.13.1 🤔
