### ISSUE TITLE
`bin/biwas` fails on zero-argument procedures.

### ISSUE THREAD

**Issue by HugoNikanor** [biwascheme/biwascheme#199]
Running biwas on node fails on any zero argument procedure. To reproduce.

    biwascheme> (lambda () 1)

```
ReferenceError: BiwaScheme is not defined []
    at Object.to_set (/home/hugo/code/biwascheme/release/node_biwascheme.js:26:5)
    at klass._compile_lambda (/home/hugo/code/biwascheme/release/node_biwascheme.js:3814:45)
    at klass.compile (/home/hugo/code/biwascheme/release/node_biwascheme.js:3624:25)
    at klass.run (/home/hugo/code/biwascheme/release/node_biwascheme.js:3836:17)
    at klass.resume (/home/hugo/code/biwascheme/release/node_biwascheme.js:3067:33)
    at klass.evaluate (/home/hugo/code/biwascheme/release/node_biwascheme.js:3042:19)
    at Object.run (/home/hugo/code/biwascheme/release/node_biwascheme.js:9993:15)
    at Interface.<anonymous> (/home/hugo/code/biwascheme/bin/biwas:79:33)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
ReferenceError: BiwaScheme is not defined []
    at Object.to_set (/home/hugo/code/biwascheme/release/node_biwascheme.js:26:5)
    at klass._compile_lambda (/home/hugo/code/biwascheme/release/node_biwascheme.js:3814:45)
    at klass.compile (/home/hugo/code/biwascheme/release/node_biwascheme.js:3624:25)
    at klass.run (/home/hugo/code/biwascheme/release/node_biwascheme.js:3836:17)
    at klass.resume (/home/hugo/code/biwascheme/release/node_biwascheme.js:3067:33)
    at klass.evaluate (/home/hugo/code/biwascheme/release/node_biwascheme.js:3042:19)
    at Object.run (/home/hugo/code/biwascheme/release/node_biwascheme.js:9993:15)
    at Interface.<anonymous> (/home/hugo/code/biwascheme/bin/biwas:79:33)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
```

Tested on cf2ed64930c1a7f816b40f710939431fbdf7de3d.

**Comment by yhara** [comment]
Confirmed with [current HEAD](975cf3f). Thank you for reporting!

This does not happen with [v0.7.0](https://www.biwascheme.org/) (regression).
