### ISSUE TITLE
Is there a bug in the `call`?

### ISSUE THREAD

**Issue by dasheng523** [biwascheme/biwascheme#248]
Below is the test code

```
define_libfunc("trycall", 3, 3, function(ar){
  var f = ar[0];
  var onSuccess = ar[1];
  var onError = ar[2];
  return new Call(f, [], function(ar2) {
    var result = ar2[0];
    if (result instanceof Error) {
      return new Call(onError, [result]);
    } else {
      return new Call(onSuccess, [result]);
    }
  });
});

define_libfunc("promise-wait", 1, 1, function(ar){
  var p = ar[0];
  return new Pause(function(pause){
    p.catch(function(e) { pause.resume(new Error(e)) })
      .then(function(rs) { pause.resume(rs) });
  });
});

(display
 (trycall
  (lambda () (promise-wait (js-eval "new Promise(function(resolve, reject){ throw new Error('Test Error') })")))
  (lambda (e) "print ok")
  (lambda (e) "print error")))

```

repl message:

```
print errorE:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:1236
  if (obj.to_display) return obj.to_display(to_display);
          ^

TypeError: Cannot read property 'to_display' of undefined
    at to_display (E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:1236:11)
    at E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:8679:19
    at f (E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:4194:12)
    at klass._execute (E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:3752:26)
    at klass.resume (E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:3864:20)
    at klass.resume (E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:1365:29)
    at E:\project\sicp\front\node_modules\biwascheme\release\node_biwascheme.js:5594:13
```

It printed `print error`, but it also threw an exception.

**Comment by yhara** [comment]
This was a bug of `display` rather than `Call`. Fixed by #249.

**Comment by dasheng523** [comment]
But why `display` is called twice

**Comment by yhara** [comment]
> console output: errorundefined

I got the same result. 🤔

**Comment by yhara** [comment]
Ok I found why:
```js
define_libfunc("promise-wait", 1, 1, function(ar){
  var p = ar[0];
  return new Pause(function(pause){
    p.catch(function(e) { pause.resume(new Error(e)) })
      .then(function(rs) { pause.resume(rs) });
  });
});
```
In this case `then` and `catch` is not exclusive; `then` clause is executed even when it caught an error with `catch`.
To make them exclusive, you can [pass two functions for `then`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then).
```js
define_libfunc("promise-wait", 1, 1, function(ar){
  var p = ar[0];
  return new Pause(function(pause){
    p.then(function(rs) { pause.resume(rs) },
           function(e) { pause.resume(new Error(e)) })
  });
});
```

**Comment by dasheng523** [comment]
どうもありがとうございました
