### ISSUE TITLE
load function doesn't load files from current directory

### ISSUE THREAD

**Issue by ktodyruik-ipl** [biwascheme/biwascheme#89]
Hi,

I created a file in the current directory called 'test.scm'. Started the repl with 'biwas'. Typed (load "test.scm") and got this error:

```
biwascheme> (load "test.scm")
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/biwascheme/release/../../../test.scm' [load]
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /usr/local/lib/node_modules/biwascheme/release/node_biwascheme.js:8082:28
    at f (/usr/local/lib/node_modules/biwascheme/release/node_biwascheme.js:3281:12)
    at BiwaScheme.Interpreter.BiwaScheme.Class.create._execute (/usr/local/lib/node_modules/biwascheme/release/node_biwascheme.js:2957:24)
    at BiwaScheme.Interpreter.BiwaScheme.Class.create.resume (/usr/local/lib/node_modules/biwascheme/release/node_biwascheme.js:3080:20)
    at BiwaScheme.Interpreter.BiwaScheme.Class.create.evaluate (/usr/local/lib/node_modules/biwascheme/release/node_biwascheme.js:3049:19)
    at Object.BiwaScheme.run (/usr/local/lib/node_modules/biwascheme/release/node_biwascheme.js:8068:15)
    at Interface.<anonymous> (/usr/local/lib/node_modules/biwascheme/bin/biwas:78:33)
biwascheme> 

```

**Comment by amirouche** [comment]
You can rebind the nodejs API yourself, using the [`js-*` procedures](http://www.biwascheme.org/doc/reference.html#javascript-language-interface) .

(That's what I do browser find for the xhr procedure `http-request` into a `$.ajax` because the rendering must be synchronous most of the time. Greenthreads are part of the API, but not web workers yet.)

**Comment by yhara** [comment]
This is a terrible bug ...
Please use this patch until it is fixed.

```scheme
(define (load path)
  (eval (read-from-string
    (js-invoke (js-eval "require('fs')") 'readFileSync path "utf-8"))))

(load "b.scm")
```

Note: The `path` above is relative to the current directory, but I'd like to make it relative to the current source file, like [`require` of Node.js](https://nodejs.org/api/modules.html#modules_modules).

**Comment by yhara** [comment]
> ... but I'd like to make it relative to the current source file, like require of Node.js.

After rethinking, fixed `load` to find relative path from the current directory. The behavior above 
 should be a different function like `load-relative`.
